version: '3.7'
services:
  db:
    container_name: dbTest
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Password1
      MYSQL_DATABASE: testDB

    ports:
      # just if you also want to access it directly from you host
      # node neede for phpmyadmin
      - "1433:1433"
    networks: 
      - web
  phpmyadmin:
    container_name: phpmyadminTest
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    networks: 
      - web
    environment:
      PMA_PORT: 3306
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: Password1

networks: 
  web:
    name: testNetwork
    driver: bridge
